# -*- coding: utf-8 -*-

"""
   MagicTelecomAPILib.Controllers.DidsProductsController

   This file was automatically generated by APIMATIC BETA v2.0 on 06/22/2016
"""
from MagicTelecomAPILib.APIHelper import APIHelper
from MagicTelecomAPILib.APIException import APIException
from MagicTelecomAPILib.Configuration import Configuration
from MagicTelecomAPILib.Http.HttpRequest import HttpRequest
from MagicTelecomAPILib.Http.HttpResponse import HttpResponse
from MagicTelecomAPILib.Http.RequestsClient import RequestsClient
from MagicTelecomAPILib.Controllers.BaseController import BaseController



class DidsProductsController(BaseController):

    """A Controller to access Endpoints in the MagicTelecomAPILib API."""

    def __init__(self, http_client = None):
        """Constructor which allows a different HTTP client for this controller."""
        BaseController.__init__(self, http_client)

    def get_dids(self,
                 page=None,
                 limit=None,
                 filter=None):
        """Does a GET request to /dids/products/dids.

        Allow clients to get the list of available phone_numbers

        Args:
            page (int, optional): Zero based offset index for the results.
                e.g. 0 would start at the first result and 10 would start at
                the eleventh result
            limit (int, optional): Maximum number of results to return in the
                response
            filter (string, optional): Allowed fields: country_iso2,
                region_handle, location_handle, location_name, phone_number,
                phone_number_type, zip_code

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/dids"

        # Process optional query parameters
        query_parameters = {
            "page": page,
            "limit": limit,
            "filter": filter
        }
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers, query_parameters=query_parameters)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body



    def get_dids_by_phone_number(self,
                                 phone_number):
        """Does a GET request to /dids/products/dids/{phone_number}.

        Allow clients to get a specific phone_number

        Args:
            phone_number (string): Phone Number

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/dids/{phone_number}"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "phone_number": phone_number
        })
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body



    def get_locations(self,
                      page=None,
                      limit=None,
                      filter=None):
        """Does a GET request to /dids/products/locations.

        Allow clients to get the list of available locations.

        Args:
            page (int, optional): Zero based offset index for the results.
                e.g. 0 would start at the first result and 10 would start at
                the eleventh result
            limit (int, optional): Maximum number of results to return in the
                response
            filter (string, optional): Allowed fields: country_iso2,
                region_handle, location_handle, location_name, prefix,
                phone_number_type, zip_code, npa, nxx, fax

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/locations"

        # Process optional query parameters
        query_parameters = {
            "page": page,
            "limit": limit,
            "filter": filter
        }
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers, query_parameters=query_parameters)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body



    def get_location_by_handle(self,
                               location_handle):
        """Does a GET request to /dids/products/locations/{location_handle}.

        Allow clients to get a specific location.

        Args:
            location_handle (string): Location Handle

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/locations/{location_handle}"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "location_handle": location_handle
        })
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body



    def get_trunks(self,
                   page=None,
                   limit=None):
        """Does a GET request to /dids/products/trunks.

        Allow clients to get the list of available trunks

        Args:
            page (int, optional): Zero based offset index for the results.
                e.g. 0 would start at the first result and 10 would start at
                the eleventh result
            limit (int, optional): Maximum number of results to return in the
                response

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/trunks"

        # Process optional query parameters
        query_parameters = {
            "page": page,
            "limit": limit
        }
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers, query_parameters=query_parameters)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body



    def get_trunk_by_handle(self,
                            trunk_handle):
        """Does a GET request to /dids/products/trunks/{trunk_handle}.

        Allow clients to get a specific trunk

        Args:
            trunk_handle (string): Trunk Handle

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/trunks/{trunk_handle}"

        # Process optional template parameters
        query_builder = APIHelper.append_url_with_template_parameters(query_builder, { 
            "trunk_handle": trunk_handle
        })
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body



    def get_countries_by_trunk(self,
                               page,
                               limit):
        """Does a GET request to /dids/products/trunks/countries.

        Allow clients to get trunk zones.

        Args:
            page (int): Zero based offset index for the results. e.g. 0 would
                start at the first result and 10 would start at the eleventh
                result.
            limit (int): Maximum number of results to return in the response.

        Returns:
            mixed: Response from the API. 

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        # The base uri for api requests
        query_builder = Configuration.BASE_URI
 
        # Prepare query string for API call
        query_builder += "/dids/products/trunks/countries"

        # Process optional query parameters
        query_parameters = {
            "page": page,
            "limit": limit
        }
        
        # Validate and preprocess url
        query_url = APIHelper.clean_url(query_builder)

        # Prepare headers
        headers = {
            "user-agent": "APIMATIC 2.0",
            "accept": "application/json",
            "X-Auth-Token": Configuration.x_auth_token,
            "X-Auth-Token": Configuration.x_auth_token
        }

        # Prepare the API call.
        http_request = self.http_client.get(query_url, headers=headers, query_parameters=query_parameters)

        # Invoke the API call  to fetch the response.
        response = self.http_client.execute_as_string(http_request);

        # Endpoint error handling using HTTP status codes.
        if response.status_code == 401:
            raise APIException("You are not authenticated", 401, response.raw_body)
        elif response.status_code == 403:
            raise APIException("This action needs a valid WSSE header", 403, response.raw_body)
        elif response.status_code == 404:
            raise APIException("Resource not found", 404, response.raw_body)

        # Global error handling using HTTP status codes.
        self.validate_response(response)    

        return response.raw_body


