# -*- coding: utf-8 -*-

"""
   MagicTelecomAPILib.Configuration

   This file was automatically generated by APIMATIC v2.0 on 06/22/2016
"""

class Configuration(object):
    # The base Uri for API calls
    BASE_URI = "https://api.magictelecom.com/app_dev.php"

    # API Token
    x_auth_token = "123abcqwerty";


