# -*- coding: utf-8 -*-

"""
   MagicTelecomAPILib.Models.Account
 
   This file was automatically generated by APIMATIC v2.0 on 06/22/2016
"""
from MagicTelecomAPILib.APIHelper import APIHelper

class Account(object):

    """Implementation of the 'Account' model.

    TODO: type model description here.

    Attributes:
        number (string): TODO: type description here.
        roles (list of string): TODO: type description here.
        email (string): TODO: type description here.
        contact_number (string): TODO: type description here.
        firstname (string): TODO: type description here.
        lastname (string): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the Account class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    number -- string -- Sets the attribute number
                    roles -- list of string -- Sets the attribute roles
                    email -- string -- Sets the attribute email
                    contact_number -- string -- Sets the attribute contact_number
                    firstname -- string -- Sets the attribute firstname
                    lastname -- string -- Sets the attribute lastname
        
        """
        # Set all of the parameters to their default values
        self.number = None
        self.roles = None
        self.email = None
        self.contact_number = None
        self.firstname = None
        self.lastname = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "number": "number",
            "roles": "roles",
            "email": "email",
            "contact_number": "contact_number",
            "firstname": "firstname",
            "lastname": "lastname",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "number": "number",
            "roles": "roles",
            "email": "email",
            "contact_number": "contact_number",
            "firstname": "firstname",
            "lastname": "lastname",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)