# -*- coding: utf-8 -*-

"""
   MagicTelecomAPILib.Models.CallerLocation
 
   This file was automatically generated by APIMATIC v2.0 on 06/22/2016
"""
from MagicTelecomAPILib.APIHelper import APIHelper

class CallerLocation(object):

    """Implementation of the 'Caller Location' model.

    A caller location

    Attributes:
        name (string): Location Name
        address (string): Address
        city (string): City
        region (string): Region
        postal_code (int): Postal Code
        unit_type (string): Unit Type
        unit_number (int): Unit Number
        country (string): Country Name

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the CallerLocation class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    name -- string -- Sets the attribute name
                    address -- string -- Sets the attribute address
                    city -- string -- Sets the attribute city
                    region -- string -- Sets the attribute region
                    postal_code -- int -- Sets the attribute postal_code
                    unit_type -- string -- Sets the attribute unit_type
                    unit_number -- int -- Sets the attribute unit_number
                    country -- string -- Sets the attribute country
        
        """
        # Set all of the parameters to their default values
        self.name = None
        self.address = None
        self.city = None
        self.region = None
        self.postal_code = None
        self.unit_type = None
        self.unit_number = None
        self.country = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "name": "name",
            "address": "address",
            "city": "city",
            "region": "region",
            "postal_code": "postal_code",
            "unit_type": "unit_type",
            "unit_number": "unit_number",
            "country": "country",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "name": "name",
            "address": "address",
            "city": "city",
            "region": "region",
            "postal_code": "postal_code",
            "unit_type": "unit_type",
            "unit_number": "unit_number",
            "country": "country",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)