# -*- coding: utf-8 -*-

"""
   MagicTelecomAPILib.Models.TelephoneNumber
 
   This file was automatically generated by APIMATIC v2.0 on 06/22/2016
"""
from MagicTelecomAPILib.APIHelper import APIHelper
from MagicTelecomAPILib.Models.RoutingBase import RoutingBase

class TelephoneNumber(object):

    """Implementation of the 'Telephone Number' model.

    TODO: type model description here.

    Attributes:
        trunk_id (int): TODO: type description here.
        sip_end_point_uri (string): TODO: type description here.
        alias (string): TODO: type description here.
        channels (int): TODO: type description here.
        routing (RoutingBase): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the TelephoneNumber class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    trunk_id -- int -- Sets the attribute trunk_id
                    sip_end_point_uri -- string -- Sets the attribute sip_end_point_uri
                    alias -- string -- Sets the attribute alias
                    channels -- int -- Sets the attribute channels
                    _routing -- RoutingBase -- Sets the attribute routing
        
        """
        # Set all of the parameters to their default values
        self.trunk_id = None
        self.sip_end_point_uri = None
        self.alias = None
        self.channels = None
        self.routing = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "trunk_id": "trunk_id",
            "sip_end_point_uri": "sip_end_point_uri",
            "alias": "alias",
            "channels": "channels",
            "_routing": "routing",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "_routing" in kwargs:
                self.routing = RoutingBase(**kwargs["_routing"])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "trunk_id": "trunk_id",
            "sip_end_point_uri": "sip_end_point_uri",
            "alias": "alias",
            "channels": "channels",
            "routing": "_routing",
        }

        retval = dict()

        return APIHelper.resolve_names(self, replace_names, retval)