# -*- coding: utf-8 -*-

"""
   MagicTelecomAPILib.Models.TrunkItem
 
   This file was automatically generated by APIMATIC v2.0 on 06/22/2016
"""
from MagicTelecomAPILib.APIHelper import APIHelper
from MagicTelecomAPILib.Models.Item import Item
from MagicTelecomAPILib.Models.Routing import Routing

class TrunkItem(Item):

    """Implementation of the 'Trunk Item' model.

    Trunk Item
    NOTE: This class inherits from 'Item'.

    Attributes:
        channels (int): TODO: type description here.
        trunk_handle (string): TODO: type description here.
        sip_uri (string): TODO: type description here.
        attributes (string): TODO: type description here.
        routing (Routing): TODO: type description here.

    """

    def __init__(self,
                 **kwargs):
        """Constructor for the TrunkItem class
        
        Args:
            **kwargs: Keyword Arguments in order to initialise the
                object. Any of the attributes in this object are able to
                be set through the **kwargs of the constructor. The values
                that can be supplied and their types are as follows::

                    channels -- int -- Sets the attribute channels
                    trunk_handle -- string -- Sets the attribute trunk_handle
                    sip_uri -- string -- Sets the attribute sip_uri
                    attributes -- string -- Sets the attribute attributes
                    _routing -- Routing -- Sets the attribute routing
                    item_type -- string -- Sets the attribute item_type
        
        """
        # Call the constructor for the base class
        super(TrunkItem, self).__init__(**kwargs)

        # Set all of the parameters to their default values
        self.channels = None
        self.trunk_handle = None
        self.sip_uri = None
        self.attributes = None
        self.routing = None
        self.item_type = None

        # Create a mapping from API property names to Model property names
        replace_names = {
            "channels": "channels",
            "trunk_handle": "trunk_handle",
            "sip_uri": "sip_uri",
            "attributes": "attributes",
            "_routing": "routing",
            "item_type": "item_type",
        }

        # Parse all of the Key-Value arguments
        if kwargs is not None:
            for key in kwargs:
                # Only add arguments that are actually part of this object
                if key in replace_names:
                    setattr(self, replace_names[key], kwargs[key])

            # Other objects also need to be initialised properly
            if "_routing" in kwargs:
                self.routing = Routing(**kwargs["_routing"])

    def resolve_names(self):
        """Creates a dictionary representation of this object.
        
        This method converts an object to a dictionary that represents the
        format that the model should be in when passed into an API Request.
        Because of this, the generated dictionary may have different
        property names to that of the model itself.
        
        Returns:
            dict: The dictionary representing the object.
        
        """
        # Create a mapping from Model property names to API property names
        replace_names = {
            "channels": "channels",
            "trunk_handle": "trunk_handle",
            "sip_uri": "sip_uri",
            "attributes": "attributes",
            "routing": "_routing",
            "item_type": "item_type",
        }

        # Start from the base class
        retval = super(TrunkItem, self).resolve_names()

        return APIHelper.resolve_names(self, replace_names, retval)